/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traitement_image;
import org.apache.commons.io.FileUtils;
import java.awt.Color;
import java.awt.FileDialog;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.awt.image.ImageFilter;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.PathMatcher;
import java.nio.file.Paths;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author oussama
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jSlider3 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane1.setViewportView(jLabel5);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane3.setViewportView(jLabel4);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setForeground(new java.awt.Color(102, 102, 102));

        jPanel2.setName("taitement d'image"); // NOI18N

        jSlider1.setMajorTickSpacing(50);
        jSlider1.setMaximum(255);
        jSlider1.setMinorTickSpacing(10);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("           IMAGE ROUGE");

        jSlider2.setMajorTickSpacing(50);
        jSlider2.setMaximum(255);
        jSlider2.setMinorTickSpacing(10);
        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setValue(0);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setText("             IMAGE  VERT");

        jSlider3.setMajorTickSpacing(50);
        jSlider3.setMaximum(255);
        jSlider3.setMinorTickSpacing(10);
        jSlider3.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider3.setPaintLabels(true);
        jSlider3.setPaintTicks(true);
        jSlider3.setValue(0);
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("           IMAGE  BLUE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);
        jPanel2.getAccessibleContext().setAccessibleName("");

        jButton1.setText("comparer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitement_image/system-search-32.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("     choisir dir:");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "C", "D", "E", "F", "G" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("  recherche sur :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
        });

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitement_image/53.png"))); // NOI18N
        jMenu1.setText("File");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitement_image/blue-folder-open-image.png"))); // NOI18N
        jMenu3.setText(" ouvrir  image");
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuSelected(evt);
            }
        });
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitement_image/save_16.png"))); // NOI18N
        jMenu2.setText("sauvguarder");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitement_image/image-16.png"))); // NOI18N
        jMenu7.setText("image naturel");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        jMenu12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitement_image/647709-image-16.png"))); // NOI18N
        jMenu12.setText("image sépia");
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu12);

        jMenu4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitement_image/icon-image-16.png"))); // NOI18N
        jMenu4.setText("noir et blanc");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu5.setIcon(new javax.swing.ImageIcon("E:\\PROGRAMMATION\\JAVA TRAITEMEN DES IMAGES\\icon\\647715-image-16.png")); // NOI18N
        jMenu5.setText("image negatif");
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuSelected(evt);
            }
        });
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu5MouseExited(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitement_image/shape_flip_horizontal.png"))); // NOI18N
        jMenu6.setText("reflexion horisontale");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitement_image/shape_flip_vertical.png"))); // NOI18N
        jMenu9.setText("reflexion verticale");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitement_image/select_by_difference.png"))); // NOI18N
        jMenu8.setText("comparaison avec");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitement_image/photo-24-16.png"))); // NOI18N
        jMenu10.setText(" capture image");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(504, 504, 504)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected

    }//GEN-LAST:event_jMenu1MenuSelected
//to take the file selected known for all the buttons
   
    private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected

    }//GEN-LAST:event_jMenu3MenuSelected

    private void jMenu5MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5MenuSelected
       
        
    }//GEN-LAST:event_jMenu5MenuSelected

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
 
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        //take the width and height of chosable image
        int width =img.getWidth();
        int height = img.getHeight();
        //traitement
        for (int y=0 ;y<height;y++){
            for (int x=0 ;x<width;x++){
                //take the rgb for chaque pixel
                int p =img.getRGB(x, y);
                
                int a = (p>>24)&0xff;
                int r = (p>>16)&0xff;
                int g = (p>>8)&0xff;
                int b = (p)&0xff;
                
                // to change the rgb to negative color for chaque pixel
                r=255-r;
                g=255-g;
                b=255-b;
                
                //define the new rgb for chaque pixel
                p= (a<<24)|(r<<16)|(g<<8)|(b);
                img.setRGB(x, y, p);
                
                
            }
            
        }
        ImageIcon iimg =new ImageIcon(img) ;
        jLabel5.setIcon(iimg);
        
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
//OOPEN FILE CHOOSER
JFileChooser chooser = new JFileChooser () ; 
chooser.showOpenDialog(null);
//  THE NAME OF SELECTED FILE 
 f = chooser.getSelectedFile();
String s = f.getAbsolutePath();
        try {
            //  RUN THE FILE
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+s);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    //public variable for all the traitement
    //img is the image of all traitement
    BufferedImage img =null;
    //the original chosable image in jfile chooser
    File f; 
   
    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
  JFileChooser choooser = new JFileChooser () ; 
  // to update jfile chooser when new image save 
  choooser.updateUI();
//add type image to the search of  FILE CHOOSER
FileNameExtensionFilter ft = new FileNameExtensionFilter("*.Image","jpg", "png", "gif");
choooser.addChoosableFileFilter(ft);
//OPEN FILE CHOOSER
choooser.showOpenDialog(null);
 f =choooser.getSelectedFile();
    try {
         // this image will have the image of jfilechooser to all the traitement
            img = ImageIO.read(f);
            //PUT THE PATH OF SELECTED IMAGE IN NEW ICON IMAGE 
           String path = choooser.getSelectedFile().getAbsolutePath();
         ImageIcon iimg =new ImageIcon(path) ;
         // put new icon in jlabel in reseysable panel (scroll pan) because the differnce between taille image et taille jlabel
            jLabel5.setIcon(iimg);
// TODO add your handling code here:
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    
    
    private void jMenu5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseExited

    private void jMenu5MenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5MenuDeselected

// TODO add your handling code here:*/
    }//GEN-LAST:event_jMenu5MenuDeselected

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        /*   
        int p =JOptionPane.showConfirmDialog(null, "save the change");
if (p==0){
    try {
     
        ImageIO.write(img, "jpg",f);
        
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, ex);
       
    }
  }*/
 //4/save image in CREATED file  
        //path of chosable file
    String nfile;
 //OPEN FILE DIALOG
        FileDialog fd =new FileDialog(NewJFrame.this,"save image",FileDialog.SAVE);
        fd.show();
        
        //get the CREATED file (new file to save) in file dialog
        if (fd.getFile()!= null){
            //write the full path of created file
            nfile = fd.getDirectory()+fd.getFile()+".jpg";
            //take path in new file
            File make = new File(nfile);
            
            try {
                //write image in file
                ImageIO.write((RenderedImage) img, "jpg", make);
            } catch (IOException ex) {
                Logger.getLogger(Webcam_form.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
   //take the width and height of chosable image
        int width =img.getWidth();
        int height = img.getHeight();
        //traitement
        for (int y=0 ;y<height;y++){
            for (int x=0 ;x<width;x++){
                //take the rgb for chaque pixel
                int p =img.getRGB(x, y);
                
                int a = (p>>24)&0xff;
                int r = (p>>16)&0xff;
                int g = (p>>8)&0xff;
                int b = (p)&0xff;
                
                // to change the rgb to negative color for chaque pixel
                int avg =(r+g+b)/3;
                
                //define the new rgb for chaque pixel
                p= (a<<24)|(avg<<16)|(avg<<8)|(avg);
                img.setRGB(x, y, p);
                
                
            }
            
        }
        ImageIcon iimg =new ImageIcon(img) ;
        jLabel5.setIcon(iimg);
                // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
 try {
         // this image will have the image of jfilechooser to all the traitement
            img = ImageIO.read(f);
            //PUT THE PATH OF SELECTED IMAGE IN NEW ICON IMAGE 
           String path = f.getAbsolutePath();
         ImageIcon iimg =new ImageIcon(path) ;
         // put new icon in jlabel in reseysable panel (scroll pan) because the differnce between taille image et taille jlabel
            jLabel5.setIcon(iimg);
// TODO add your handling code here:
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7MouseClicked
 
    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
   
     
        
        // horisontaly flip
        AffineTransform tx=AffineTransform.getScaleInstance(-1.0,1.0);  //scaling
     tx.translate(-img.getWidth(),0);  //translating
     //add the the transformation and source image to result image transformé
     AffineTransformOp tr=new AffineTransformOp(tx,null);  //transforming
   img= tr.filter(img, null); 
    
    
  /////////BufferedImage iimmg = new BufferedImage(img.getWidth(),img.getHeight(),img.getType());
   //////////////   iimmg= tr.filter(img, null); 
        
        ImageIcon iimg =new ImageIcon(img) ;
        jLabel5.setIcon(iimg);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
         //verticaly flip
        AffineTransform tx=AffineTransform.getScaleInstance(1.0,-1.0);  //scaling
     tx.translate(0,-img.getHeight());  //translating
       //add the the transformation and source image to result image transformé
     AffineTransformOp tr=new AffineTransformOp(tx,null); 
     img= tr.filter(img, null); 
        
        ImageIcon iimg =new ImageIcon(img) ;
        jLabel5.setIcon(iimg);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int h,w;
        try{    
    if (img.getHeight()>imgimg.getHeight()){
       h = imgimg.getHeight();
    }else{
         h = img.getHeight();
    }
    if (img.getWidth()>imgimg.getWidth()){
      w = imgimg.getWidth();
    }else{
         w = img.getWidth();
    }
    
    
        long diff = 0;
        
        //DEIIFERNCE BETWEEN ALL THE PIXELS
         for (int y=0 ;(y<h);y++){
            for (int x=0 ;(x<w);x++){
            
        int rgb1 = img.getRGB(x, y);
        int rgb2 = imgimg.getRGB(x, y);
       // FIND THE DEGREé OF ALL THE 3 COULEURS FOR 2 IMAGES
           int r1 = (rgb1 >> 16) & 0xff;
        int g1 = (rgb1 >>  8) & 0xff;
        int b1 = (rgb1      ) & 0xff;
        int r2 = (rgb2 >> 16) & 0xff;
        int g2 = (rgb2 >>  8) & 0xff;
        int b2 = (rgb2      ) & 0xff;
        // add diFFERENCE between chaque degré de couleur (max valeur 255)
       diff += Math.abs(r1 - r2);
        diff += Math.abs(g1 - g2);
        diff += Math.abs(b1 - b2);
            }}
         //CALCUL SURFACE *3 *255 (3 MEAN 3 DEGré calculé)(255 max valeur of differnce FOR CHAQUE DEGREé)
         double n = w* h * 3 * 255.0;
         //calcul percentage by 4 motanasib
    double p = (diff / n )*100.00;
         JOptionPane.showMessageDialog(null, "Pourcentage de differnce = "+p+" %");}
catch (Exception e){
    JOptionPane.showMessageDialog(this, " telecharger l'image avant ");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    BufferedImage imgimg =null;
    //the original chosable image in jfile chooser
    File ff; 
    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
       
        
         JFileChooser chooooser = new JFileChooser () ; 
  // to update jfile chooser when new image save 
  chooooser.updateUI();
//add type image to the search of  FILE CHOOSER
FileNameExtensionFilter ft = new FileNameExtensionFilter("*.Image","jpg", "png", "gif");
chooooser.addChoosableFileFilter(ft);
//OPEN FILE CHOOSER
chooooser.showOpenDialog(null);
 ff =chooooser.getSelectedFile();
    try {
         // this image will have the image of jfilechooser to all the traitement
            imgimg= ImageIO.read(ff);
            //PUT THE PATH OF SELECTED IMAGE IN NEW ICON IMAGE 
           String path = chooooser.getSelectedFile().getAbsolutePath();
         ImageIcon iimg =new ImageIcon(path) ;
         // put new icon in jlabel in reseysable panel (scroll pan) because the differnce between taille image et taille jlabel
            jLabel4.setIcon(iimg);
// TODO add your handling code here:
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }        // TODO add your handling code here:
                 
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged
        int width =img.getWidth();
        int height = img.getHeight();
        //traitement
        for (int y=0 ;y<height;y++){
            for (int x=0 ;x<width;x++){
                //take the rgb for chaque pixel
                int p =img.getRGB(x, y);

                int a = (p>>24)&0xff;
                int r = (p>>16)&0xff;
                int g = (p>>8)&0xff;
                int b = (p)&0xff;

                // to change the rgb to negative color for chaque pixel
                b=jSlider3.getValue();

                //define the new rgb for chaque pixel
                p= (a<<24)|(r<<16)|(g<<8)|(b);
                img.setRGB(x, y, p);

            }

        }
        ImageIcon iimg =new ImageIcon(img) ;
        jLabel5.setIcon(iimg);         // TODO add your handling code here:
    }//GEN-LAST:event_jSlider3StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        int width =img.getWidth();
        int height = img.getHeight();
        //traitement
        for (int y=0 ;y<height;y++){
            for (int x=0 ;x<width;x++){
                //take the rgb for chaque pixel
                int p =img.getRGB(x, y);

                int a = (p>>24)&0xff;
                int r = (p>>16)&0xff;
                int g = (p>>8)&0xff;
                int b = (p)&0xff;

                // to change the rgb to negative color for chaque pixel
                g=jSlider2.getValue();

                //define the new rgb for chaque pixel
                p= (a<<24)|(r<<16)|(g<<8)|(b);
                img.setRGB(x, y, p);

            }

        }
        ImageIcon iimg =new ImageIcon(img) ;
        jLabel5.setIcon(iimg);         // TODO add your handling code here:
    }//GEN-LAST:event_jSlider2StateChanged

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        int width =img.getWidth();
        int height = img.getHeight();
        //traitement
        for (int y=0 ;y<height;y++){
            for (int x=0 ;x<width;x++){
                //take the rgb for chaque pixel
                int p =img.getRGB(x, y);

                int a = (p>>24)&0xff;
                int r = (p>>16)&0xff;
                int g = (p>>8)&0xff;
                int b = (p)&0xff;

                // to change the rgb to negative color for chaque pixel
                r=jSlider1.getValue();

                //define the new rgb for chaque pixel
                p= (a<<24)|(r<<16)|(g<<8)|(b);
                img.setRGB(x, y, p);

            }

        }
        ImageIcon iimg =new ImageIcon(img) ;
        jLabel5.setIcon(iimg);        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider1StateChanged

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
   //take the width and height of chosable image
        int width =img.getWidth();
        int height = img.getHeight();
        //traitement
        for (int y=0 ;y<height;y++){
            for (int x=0 ;x<width;x++){
                //take the rgb for chaque pixel
                int p =img.getRGB(x, y);
                
                int a = (p>>24)&0xff;
                int r = (p>>16)&0xff;
                int g = (p>>8)&0xff;
                int b = (p)&0xff;
                
                // calculate tr ,tg ,tb
                int tr=(int)(0.393 *r+0.769*g+0.189*b);
               int tg=(int)(0.349 *r+0.686*g+0.168*b);
               int tb=(int)(0.272 *r+0.534*g+0.131*b);
                // test the conditions
               if (tr>255){
                   r=255;
               }else{
                   r= tr;
               }
               
               if (tg>255){
                   r=255;
               }else{
                   r= tg;
               }
               
               if (tb>255){
                   r=255;
               }else{
                   r= tb;
               }
              
                //define the new rgb for chaque pixel
                p= (a<<24)|(r<<16)|(g<<8)|(b);
                img.setRGB(x, y, p);
                
                
            }
            
        }
        ImageIcon iimg =new ImageIcon(img) ;
        jLabel5.setIcon(iimg);
                // TODO add your handling code here:
    }//GEN-LAST:event_jMenu12MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            //the directory when i search for file
        String a =jList1.getSelectedValue().toString();
        File root = new File(a+":\\");
        // THE FILE THAT I LOOK FOR IT
            String fileName = jTextField1.getText();
            
            try {
                boolean recursive = true;
                 /////////////////////////////////////////////////////////////
                  //DESIGNE ALL THE FILES OF THE DIR
                Collection files = FileUtils.listFiles(root, null, recursive);

                //// BOUCLE (FOR) to walk on COLLECTION (all file of chosable dir)
                for (Iterator iterator = files.iterator(); iterator.hasNext();) {
                   // CHANGE TYPE OF ITERATOR OF COLLECTION TO FILE
                    File file = (File) iterator.next();
                    // CAMPARAISON BETWEEN SEARCHED FILE AND FILE OF THIS BOUCLE
                    if (file.getName().equals(fileName)){
                    
      ////////////////////////////////////////////////////////////////////////////////////                      
        //CHANGE CONSTUCTER TO OPEN JFILE CHOOSER IN SPECIFIED FILE (file parent fo searched file
                             JFileChooser choooser = new JFileChooser (file.getParentFile()) ; 
  

//OPEN FILE CHOOSER
choooser.showOpenDialog(null);

                  // to update jfile chooser when new image save 
  choooser.updateUI();  
  f =choooser.getSelectedFile();
    try {
         // this image will have the image of jfilechooser to all the traitement
            img = ImageIO.read(f);
            //PUT THE PATH OF SELECTED IMAGE IN NEW ICON IMAGE 
           String path = choooser.getSelectedFile().getAbsolutePath();
         ImageIcon iimg =new ImageIcon(path) ;
         // put new icon in jlabel in reseysable panel (scroll pan) because the differnce between taille image et taille jlabel
            jLabel5.setIcon(iimg);
                   }    catch (IOException ex) {
                             JOptionPane.showMessageDialog(null,ex);
                        }}}
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
           }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
Webcam_form f =new Webcam_form();
f.setBounds(330, 200, 690, 400);
f.setVisible(true);
      
    }//GEN-LAST:event_jMenu10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
