/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traitement_image;

import java.awt.FileDialog;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.media.Buffer;
import javax.media.CannotRealizeException;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.NoPlayerException;
import javax.media.Player;
import javax.media.control.FrameGrabbingControl;
import javax.media.format.VideoFormat;
import javax.media.util.BufferToImage;
import javax.swing.ImageIcon;

/**
 *
 * @author oussama
 */
public class Webcam_form extends javax.swing.JFrame {
Player player;
    /**
     * Creates new form Webcam_form
     */
    public Webcam_form()  {
        initComponents();
        
        
        //2/it's the fonction to start camera in jtagled button it's in down and i call it here
    try {
        initCamera();
    } catch (IOException ex) {
        Logger.getLogger(Webcam_form.class.getName()).log(Level.SEVERE, null, ex);
    } catch (NoPlayerException ex) {
        Logger.getLogger(Webcam_form.class.getName()).log(Level.SEVERE, null, ex);
    } catch (CannotRealizeException ex) {
        Logger.getLogger(Webcam_form.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    //1/the fonction to start camera in jtagled button
    //////CREATE NEW IVIDEO PLAYER & MEDIA LOCATOR () HADHIKA NJIBOUHA MIN JMF LIZ IDTAH
    private void initCamera()throws IOException,NoPlayerException,CannotRealizeException{
        MediaLocator ml= new MediaLocator("vfw://0");
        player = Manager.createRealizedPlayer(ml);
        ///// NDHIF LVIDEO LL TAGLED BUTTON( MSAMIHA tbcamera)
        this.tbcamera.add(player.getVisualComponent());
        //NABDA TASWIR
        player.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbcamera = new javax.swing.JToggleButton();
        bsave = new javax.swing.JButton();
        bcapture = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcapture = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(0, 0));

        tbcamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbcameraActionPerformed(evt);
            }
        });

        bsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitement_image/save_16.png"))); // NOI18N
        bsave.setText("sauvguarder");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });

        bcapture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitement_image/photo-24-16.png"))); // NOI18N
        bcapture.setText("capturer");
        bcapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaptureActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("              Capturer et sauvguarser image");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 102, 102)));

        jScrollPane1.setViewportView(tbcapture);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(tbcamera, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(bcapture, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bsave)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bsave)
                            .addComponent(bcapture)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(tbcamera, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbcameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbcameraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbcameraActionPerformed
 
   Image image;
    private void bcaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaptureActionPerformed
//3/ take photo and pose it in jtaglesbutton2
        ///grab an image
        FrameGrabbingControl fgc = (FrameGrabbingControl)player.getControl("javax.media.control.FrameGrabbingControl");
Buffer buffer = fgc.grabFrame();
BufferToImage bti = new BufferToImage((VideoFormat)buffer.getFormat());
//take grab in image
 image = bti.createImage(buffer);
// how to resize it
// TAKE IMAGE IN JTGLEDBUTO CALLED (tbcapture)
        ImageIcon im = new ImageIcon(image);
        this.tbcapture.setIcon(im);




// TODO add your handling code here:
    }//GEN-LAST:event_bcaptureActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
     //4/save image in CREATED file  
        //path of chosable file
    String nfile;
 //OPEN FILE DIALOG
        FileDialog fd =new FileDialog(Webcam_form.this,"save image",FileDialog.SAVE);
        fd.show();
        
        //get the CREATED file (new file to save) in file dialog
        if (fd.getFile()!= null){
            //write the full path of created file
            nfile = fd.getDirectory()+fd.getFile()+".jpg";
            //take path in new file
            File make = new File(nfile);
            
            try {
                //write image in file
                ImageIO.write((RenderedImage) image, "jpg", make);
            } catch (IOException ex) {
                Logger.getLogger(Webcam_form.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_bsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Webcam_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Webcam_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Webcam_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Webcam_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Webcam_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcapture;
    private javax.swing.JButton bsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton tbcamera;
    private javax.swing.JToggleButton tbcapture;
    // End of variables declaration//GEN-END:variables
}
